name: Publish

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      should_continue: ${{ steps.decision.outputs.continue }}
      local_version: ${{ steps.decision.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get npm version
        id: remote
        run: echo "version=$(npm show @dsplce-co/vue-modal version)" >> $GITHUB_OUTPUT
      - name: Get package version
        id: local
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - run: echo remote ${{ steps.remote.outputs.version }}
      - run: echo local ${{ steps.local.outputs.current-version }}
      - id: decision
        run: |
          if [ "${{ steps.remote.outputs.version }}" = "${{ steps.local.outputs.current-version }}" ]; then
            echo "continue=false" >> $GITHUB_OUTPUT
          else
            echo "continue=true" >> $GITHUB_OUTPUT
            echo "version=${{ steps.local.outputs.current-version }}" >> "$GITHUB_OUTPUT"
          fi

  publish:
    needs: precheck
    if: ${{ needs.precheck.outputs.should_continue == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.8.1
      - uses: actions/setup-node@v3
        with:
          node-version: 25.1.0
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
      - uses: actions/upload-artifact@v4
        with:
          name: vue-modal-${{ needs.precheck.outputs.local_version }}
          path: dist/
      - name: Create github release
        uses: v1olen/version-release-github-action@main
        with:
          download-pattern: "vue-modal-*"
          release-version: ${{ needs.precheck.outputs.local_version }}
          create-latest: "false"
